version: "3"
services:
  frontend:
    container_name: ultraskor_client
    build:
      context: ./client
      dockerfile: Dockerfile
    depends_on:
      - backend
  backend:
    container_name: ultraskor_server
    build:
      context: ./server
      dockerfile: Dockerfile
